### PR TITLE
Creating initial Embodied Carbon Dataset

### LINKED ISSUE #4: Add Embodied Carbon by Material as a Dataset
http://www.circularecology.com/embodied-energy-and-carbon-footprint-database.html#.XW6SvChKiUl

### LINKED ISSUE #6: Add method to compute embodied carbon of a BHoMObject based on volume, material and dataset
#### Description:

Picking up on your prototype script below @kayleighhoude 

EmbodiedCarbonPrototype

Converting into an initial `BH.Engine.ClimateEmergency.Compute.EmbodiedCarbon` method

### PR DESCRIPTION
**Pull request by kayleighhoude**
Added Embodied Carbon Data Set for Concrete
   
### Issues addressed by this PR

Closes #4 
Closes #6

### CODE REVIEW

**Comment by al-fisher** [comment]
@kayleighhoude pushing the initial code we started hacking together yesterday. I have put it in an initial `BH.Engine.ClimateEmergency.Compute.EmbodiedCarbon` - lots more to do to improve etc. But thought useful for you to pick up on next week as discussed 😄

**Comment by al-fisher** [comment]
Looking like this:

image

My Embodied Carbon Dataset is quite looooooong on the canvas 😆

**Comment by al-fisher** [comment]
As noted in the `Descriptions` added to the Compute.EmbodiedCarbon method. Prototype with material hardcoded as a BH.oM.Structure.MaterialFragments type - which is nicely compatible with the current BHoM Materials Dataset. However issue also raised here for discussion and further improvement https://github.com/BHoM/BHoM/issues/549

**Comment by al-fisher** [comment]
@kayleighhoude made a few tweaks to organisation of new ClimateEmergency Datasets.
1. just moved DataSets folder up to top level so easily discoverable alongside Engine and oM folders.
2. note also, I set the value of the EmbodiedCarbon parameter as type double not string in the .json file by removing the "" quotes

**Comment by al-fisher** [comment]
Will stop committing to this branch now ready for you or others to pick up tomorrow 😄

**Comment by LivAndersson** [comment]
@kayleighhoude didn't manage to build as the .json is referenced to the \ClimateEmergency_Toolkit\ClimateEmergency_oM\DataSets\ rather than just the \ClimateEmergency_Toolkit\DataSets\ where the file is located. Will you have a look at this please?

**Comment by al-fisher** [comment]
hey @LivAndersson - try now! 😄 

After rebuilding BHoM_UI on master also you should see something similar to the below in your BHoM_Datasets in say GH
image

**Pull request merged**
